# Generated by Django 5.2.3 on 2025-07-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_ticketstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontrol',
            name='app_version',
            field=models.CharField(default='1.0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='versioncontrol',
            name='ejournal',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='versioncontrol',
            name='responsible',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='versioncontrol',
            name='xfs',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.CreateModel(
            name='VersionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.versioncontrol')),
            ],
        ),
    ]
