# Generated by Django 5.2.3 on 2025-07-21 12:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_versioncomment_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVersionControl',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('firmware', models.CharField(max_length=100)),
                ('xfs', models.CharField(default='N/A', max_length=100)),
                ('ejournal', models.CharField(default='N/A', max_length=100)),
                ('responsible', models.CharField(default='N/A', max_length=100)),
                ('app_version', models.CharField(default='1.0.0', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.terminal')),
            ],
            options={
                'verbose_name': 'historical version control',
                'verbose_name_plural': 'historical version controls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
