# Generated by Django 5.2.3 on 2025-07-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_historicalversioncontrol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalVersionControl',
        ),
    ]
