# Generated by Django 5.2.3 on 2025-07-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_ticket_customer_alter_ticket_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='region',
        ),
    ]
